### ISSUE TITLE
Process Error on Kovan

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#692] opened 2021-08-31 22:46 UTC
1x process error on Kovan 
sequence number: 2143
recipient: token bridge contract

seems like an issue with a token transfer. we don't expect this. need to diagnose ASAP

**Comment by anna-carroll** [comment] 2021-08-31 22:46
(JSON files not supported)
```
[
  {
    "blockNumber": 27012910,
    "blockHash": "0xb43663f38ee7ae57163e52b1f5d8011bc3fa2b16727ace8fe75f2ac701b55250",
    "transactionIndex": 3,
    "removed": false,
    "address": "0x20AE448D61d69Dad1D5579b2AD0698Cf66b07405",
    "data": "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000006408c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001f45524332303a206d696e7420746f20746865207a65726f20616464726573730000000000000000000000000000000000000000000000000000000000",
    "topics": [
      "0xdffcee52db78cb2d1f525b8d7edd630ea062884e733aa26c201d7ce1843eccab",
      "0x1f8942e9c04ee73de901506738041eea8ae1b552fe9ae64440f8dc88f13c87ca",
      "0x000000000000000000000000000000000000000000000000000000000000085f",
      "0x0000000000000000000000005f5d96fac4cca23196531a4fa221bc309c16544e"
    ],
    "transactionHash": "0xbf7f799356d43be51b0e12cd319ca124f0b513295f35af89c36ad588c6d10452",
    "logIndex": 2,
    "event": "ProcessError",
    "eventSignature": "ProcessError(bytes32,uint32,address,bytes)",
    "args": [
      "0x1f8942e9c04ee73de901506738041eea8ae1b552fe9ae64440f8dc88f13c87ca",
      2143,
      "0x5F5D96fac4cca23196531A4Fa221bC309C16544E",
      "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001f45524332303a206d696e7420746f20746865207a65726f206164647265737300"
    ],
    "eventFragment": {
      "name": "ProcessError",
      "anonymous": false,
      "inputs": [
        {
          "name": "messageHash",
          "type": "bytes32",
          "indexed": true,
          "components": null,
          "arrayLength": null,
          "arrayChildren": null,
          "baseType": "bytes32",
          "_isParamType": true
        },
        {
          "name": "sequence",
          "type": "uint32",
          "indexed": true,
          "components": null,
          "arrayLength": null,
          "arrayChildren": null,
          "baseType": "uint32",
          "_isParamType": true
        },
        {
          "name": "recipient",
          "type": "address",
          "indexed": true,
          "components": null,
          "arrayLength": null,
          "arrayChildren": null,
          "baseType": "address",
          "_isParamType": true
        },
        {
          "name": "returnData",
          "type": "bytes",
          "indexed": false,
          "components": null,
          "arrayLength": null,
          "arrayChildren": null,
          "baseType": "bytes",
          "_isParamType": true
        }
      ],
      "type": "event",
      "_isFragment": true
    },
    "name": "ProcessError",
    "signature": "ProcessError(bytes32,uint32,address,bytes)",
    "topic": "0xdffcee52db78cb2d1f525b8d7edd630ea062884e733aa26c201d7ce1843eccab"
  }
]
```

**Comment by anna-carroll** [comment] 2021-08-31 23:18
reverted because we tried to mint tokens to the `null` address: https://dashboard.tenderly.co/tx/kovan/0xbf7f799356d43be51b0e12cd319ca124f0b513295f35af89c36ad588c6d10452/debugger?trace=0.1.1.9.1.0.7.6.1.0.2.0

this could have been because Nam tried to `send` tokens to the `null` address on kovan?  we should do some more on-chain queries to confirm that this was the user input when sending the tokens from alfajores. 

if our bridge tokens don't allow minting to the null address, we should not allow users to `send` tokens over the bridge to the `null` address (because it will fail on the other side)

**Comment by prestwich** [comment] 2021-08-31 23:34
Can confirm this seems to be user error

[See tx here](https://alfajores-blockscout.celo-testnet.org/tx/0x8c33bb01032b10a78b3c6583d3d99ad85edc554cabaf53f5c20845ae0054daf2/token-transfers)

Decoded input
```
0x1cabf08f  -- send selector
000000000000000000000000f194afdf50b03e69bd7d057c1aa9e10c9954e4c9  -- asset
000000000000000000000000000000000000000000000000000009184e72a000  -- amount
0000000000000000000000000000000000000000000000000000000000000bb8  -- destination
0000000000000000000000000000000000000000000000000000000000000000  -- recipient
```

recipient is set to 0. therefore this is behaving correctly. Nam likely stress testing the system :)

Todo: #695

**Comment by prestwich** [comment] 2021-08-31 23:36
closing issue, as we have confirmed this is correct operation

**Closed by prestwich** 2021-08-31 23:36 UTC
Labels: bug
